### ISSUE TITLE
Women's advancement voting rights 

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1514]
Contact: ami.bennitt@boston.gov

Task:
- [x] 1) The revisions to the "she votes" digital billboard signage that I sent on Friday (existing - do you have a rough estimate for when this will be done?) 
- [x] 2) New digital billboard signage for formats that differ from JC Deceaux (TD Garden version awaiting MOWA approval, do we need any others?) 
- [x] 3) Design (using "she votes" style and imagery) for 1-2 20x20 banners for City Hall
- [x] 4) Designs (using "she votes" style and imagery) of 1-3 bookmarks to be distributed through the Boston Public Library (2" by 7.25" 2-sided color bookmark (vertical))
