### ISSUE TITLE
311 App re-skin and design

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1936]
Contact: James Murphy

Files:
https://drive.google.com/open?id=1oqN8_uvV8iKJu3LxBXs6zlchdKLpNrQ_&authuser=sebastian.ebarb%40boston.gov&usp=drive_fs

Task:
- [x] 311 Welcome screen illustrations - Parent of #1908
- [ ] 311 Main App icons - Parent of #1933
- [ ] 311 In-app icons - Parent of #1934
- [ ] 311 Boston photos in app Parent of #1935

**Comment by jimmurphy-boston** [comment]
I think we can close this now, I will reach out if any more is needed,
