### ISSUE TITLE
Voting 2021 Municipal election  

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#2036]
- [x] Booklet mailer (new format) 
- [x] Bus ads 
- [x] Digital ads 
- [ ] Polling location posters 
- [ ] flyer 
- [x] Social media graphics
