### ISSUE TITLE
Public works patterns 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#2136]
Contact: Andrea Scarfo

Make patterns for all the waste streams 

- [x] Recycling: Blue #288BE4
- [x] Compost: Green #82BD55
- [x] Textile: Pink #EC638D
- [x] Leaf & Yard Waste: Orange #EE8500
- [x] E-Waste: Purple #8361A6
- [ ] Hazardous Waste: Yellow #FBB800
- [x] Trash: Grey (we have a few we can work with so feel free to pick a fave #58585B, #D2D2D2, #E0E0E0, #F2F2F2

**Comment by carolinestj** [comment]
would prefer to just have materials that are recyclable, instead of the “check” or “x”. I also prefer the see through graphics pattern personally! They look so great like that! 

My ideas for hazardous waste are paint cans, gas cans, propane tanks, batteries, tires, car parts, and bottles of chemicals. You don’t need to use all of those, just whichever are easiest for you!
