### ISSUE TITLE
Budget ads 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#2192]
Contact: Gaby Germanos

- [x] DIgital ads
- [x] Bus shelters (print) - $69 PER SHELTER FOR PRINTING
- [x] Big Belly Trash Cans (print only) - PAID
- [x] MBTA buses, trains or stations (print or digital) - PAID

**Comment by carolinestj** [comment]
BOSTON, LET'S BUDGET TOGETHER! Help inform how Boston's annual budget resources are allocated. To participate, take our survey at boston.gov/budget. Survey closes June 1, 2022." (Also include QR code)

**Comment by carolinestj** [comment]
on the "BOS-DG-506" file, "2203-01-JCD-bus-shelter-48-x70" file, "2205-bg belly budget" file, and "mbta digital screen" file, can we center the logos, instead of having them left justified? Similar to what's on the "mbta_screen 2" file.
