### ISSUE TITLE
Curbside Food Waste Collection - ads 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#2261]
Contact: Andrea Scarfo 

Due: Before June 1 

- [ ] Bus shelters (digital) - FREE
- [ ] Sidewalk kiosks (digital) - FREE
- [ ] Billboards (digital) - FREE
- [ ] Bus shelters (print) - $69 PER SHELTER FOR PRINTING
- [ ] Big Belly Trash Cans (print only) - PAID
- [ ] MBTA buses, trains or stations (print or digital) - PAID
