### ISSUE TITLE
Graphs comp request: Budget Executive Summary

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/design-team-workflow#286]
PDF exports below.

Ask: Please create Boston.gov styled graphs of the following screenshots. Please keep the same information as on each screenshot, but styled similarly to how the current budget graphs were styled (ref #179). 

Sizing: please no smaller than 250w x 300h and no larger than 350w x 425h. Ideal size is ~300w x 400h, but please keep consistency with #179 as far as standards.

Due no later than Friday 4/7 and definitely happy to receive earlier.

@sebastianebarb let me know if you have any questions or need clarification. 

For this next graph, add the graph title below the graph as part of the image.
[Title: Categories of Recurring Revenue](https://github.com/CityOfBoston/design-team-workflow/files/893485/recurring-revenue.pdf)

For this next graph, add the graph title below the graph as part of the image.
[Title: Assessed Value and Net Property Tax Growth](https://github.com/CityOfBoston/design-team-workflow/files/893488/assessed-value-net-property-tax-growth.pdf)

For this next graph:

- [ ] Add the graph title below the graph as part of the image.
- [ ] Add labels for each line (dark blue / top = "Boston's Education Spending"; green / middle = "Chapter 70 State Education Aid"; purple / bottom = "Charter School Reimbursement")
- [ ] Add label for Y axis (left vertical axis) = "($ in millions)"
- [ ] Add commas on the Y axis. E.g. "1,400" (not 1400).

[Title: Education Spending and Revenue FY14-FY18](https://github.com/CityOfBoston/design-team-workflow/files/893536/education-spending-revenue-FY14-18.pdf)

For this next graph:

- [ ] Add the graph title below the graph as part of the image
- [ ] Note that there are two versions of this graph. Use the version in RED as your example to copy from. But shade the bars according to the green-barred screenshot below the PDF upload.
[Title: Boston's Pension Funding Schedule](https://github.com/CityOfBoston/design-team-workflow/files/893624/pension-schedule.pdf)

![clear-pension-schedule](https://cloud.githubusercontent.com/assets/3886936/24664550/f0abd220-1928-11e7-9b11-d7fc11e2c4ab.PNG)

For this next graph, add the graph title below the graph as part of the image.
[Title: Cadets of Color](https://github.com/CityOfBoston/design-team-workflow/files/893640/cadets-of-color.pdf)

For this next graph, add the graph title below the graph as part of the image. Put the percentage wherever looks best.
[Title: Capital Investment in Schools](https://github.com/CityOfBoston/design-team-workflow/files/893637/capital-investment-in-schools.pdf)

This graph is a lot of content in not a lot of space. Make sure:

- [ ] labels are readable - make the graph however big it needs to be to ensure legibility of labels.
- [ ] the total graph (it's 3 graphs in one) stays the same overall shape

[Title: Impact of FY17 PAATHS Investment](https://github.com/CityOfBoston/design-team-workflow/files/893642/impact-of-paaths-investment.pdf)

**Comment by sebastianebarb** [comment]
![budget exec summary graphs-13](https://cloud.githubusercontent.com/assets/20642299/24768232/d78da64e-1acf-11e7-886d-1d6d301ceb43.png)
![budget exec summary graphs-06](https://cloud.githubusercontent.com/assets/20642299/24711973/81a38504-19ef-11e7-8c22-f7528c536e43.png)
![budget exec summary graphs-07](https://cloud.githubusercontent.com/assets/20642299/24711977/81afea4c-19ef-11e7-8e32-ed8634e0acef.png)
![budget exec summary graphs-08](https://cloud.githubusercontent.com/assets/20642299/24711979/81b91766-19ef-11e7-8645-ee4e9c480897.png)
![budget exec summary graphs-09](https://cloud.githubusercontent.com/assets/20642299/24711974/81ab892a-19ef-11e7-8c33-338155ee7213.png)
![budget exec summary graphs-10](https://cloud.githubusercontent.com/assets/20642299/24711976/81aec784-19ef-11e7-8e1e-1163831ce717.png)
![budget exec summary graphs-11](https://cloud.githubusercontent.com/assets/20642299/24711978/81b2ea80-19ef-11e7-897e-d848c15a2e4e.png)
![budget exec summary graphs-12](https://cloud.githubusercontent.com/assets/20642299/24711975/81adc83e-19ef-11e7-9e58-f379784104e4.png)

**Comment by hackajesse** [comment]
@sebastianebarb let me know if you have any questions or need clarification. 

Graphs formerly on hold: 

For this next graph:

- [ ] Add the graph title below the graph as part of the image
- [ ] Add "(dollars in millions)" to the graph
- [ ] Add dollar values for each of the sections to the graphic. 
Top (pension, debt, etc.) = $32; 
Middle (city services) = $54; 
Bottom (Education) = $58
[Budgetary Growth by Category](https://github.com/CityOfBoston/design-team-workflow/files/893555/budget-growth.pdf)


For this next graph:

- [ ] Add the graph title below the graph as part of the image.
- [ ] The end result should look like the screenshot below the PDF link.
[PDF export - Title: 1.5% Average Growth for Other 42 Departments (Not Education or Public Safety)](https://github.com/CityOfBoston/design-team-workflow/files/893563/avg-department-growth.pdf)
![screenshot](https://cloud.githubusercontent.com/assets/3886936/24768078/4f564998-1acf-11e7-8f42-eea4cb7acbe0.png)



For this next graph:

- [ ] Add the graph title below the graph as part of the image
- [ ] Add "(dollars in millions)" to the graph
- [ ] Add dollar values to each section on the graphic. 
Eliminating positions: $5
Reducing overtime: $13
Health Insurance Savings: $10
Street Light Energy Savings: $6
BPS Central Office Savings: $7
BPS Transportation Savings: $10
EMS Overtime and Revenue: $4
Other: $4
[Title: FY18 Costs Avoided through Savings Initiatives](https://github.com/CityOfBoston/design-team-workflow/files/893616/walsh-admin-savings.pdf)

**Comment by sebastianebarb** [comment]
https://github.com/CityOfBoston/design-team-workflow/issues/273

**Comment by sebastianebarb** [comment]
@hackajesse https://drive.google.com/drive/folders/0B0RwQU94BhGeT2JiaG1CRFgxVW8?usp=sharing let me know if you have issues

**Comment by hackajesse** [comment]
@sebastianebarb The graphs are looking great. Is it possible to make them slightly larger? Say 400px wide rather than 300px? If not easy, that's ok. 

Remaining edits to graphs:

[This one named budget growth by category](https://drive.google.com/open?id=0B0RwQU94BhGeVTVwWG43d1EydU0) needs the numbers on each section of the bar. 

[This one named Capital growth in schools](https://drive.google.com/open?id=0B0RwQU94BhGeUXptNVdmTEhwbHc) needs the numbers on each bar. 405 on the short one, 1,000 on the taller one.

[This one named Education Spending Revenue](https://drive.google.com/open?id=0B0RwQU94BhGecV8yVmFvMEdsUWs) needs the labels switched. Chapter 70... and Charter School Reimbursement labels should be switched (and also left aligned).

**Comment by sebastianebarb** [comment]
@hackajesse
![budget exec summary graphs-15](https://cloud.githubusercontent.com/assets/20642299/24930364/3b2d1684-1ed7-11e7-8b7c-ecc9ecc42cc6.png)
![budget exec summary graphs-16](https://cloud.githubusercontent.com/assets/20642299/24930354/36e10554-1ed7-11e7-9276-392528d387cb.png)
![budget exec summary graphs-10](https://cloud.githubusercontent.com/assets/20642299/24930353/36e01036-1ed7-11e7-822b-1f0c15417ea5.png)
![budget exec summary graphs-11](https://cloud.githubusercontent.com/assets/20642299/24930358/37199270-1ed7-11e7-9784-ef7d861df554.png)
![budget exec summary graphs-12](https://cloud.githubusercontent.com/assets/20642299/24930351/36ddf8fa-1ed7-11e7-8b39-28ee747cf0fc.png)
![budget exec summary graphs-13](https://cloud.githubusercontent.com/assets/20642299/24930352/36ddca74-1ed7-11e7-9789-f8a24d8935e3.png)
![budget exec summary graphs-06](https://cloud.githubusercontent.com/assets/20642299/24930355/36ee1532-1ed7-11e7-93ce-8ad3fd6b2a5e.png)
![budget exec summary graphs-07](https://cloud.githubusercontent.com/assets/20642299/24930356/36ee8c6a-1ed7-11e7-8f45-9ce1a5dc754c.png)
![budget exec summary graphs-08](https://cloud.githubusercontent.com/assets/20642299/24930357/37064ed6-1ed7-11e7-9904-4618595e221d.png)

![budget exec summary graphs-09](https://cloud.githubusercontent.com/assets/20642299/24930362/3928b58c-1ed7-11e7-8878-e8337fbf305d.png)
