### ISSUE TITLE
311 Design Needs

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#300]
Compilation of 311 design ticket needs:

- [x] https://github.com/CityOfBoston/design-team-workflow/issues/293
- [x] https://github.com/CityOfBoston/311/issues/206 mobile “recent requests” UI
- [ ] https://github.com/CityOfBoston/design-team-workflow/issues/259 404 and 500 page 
- [x] https://waffle.io/CityOfBoston/design-team-workflow/cards/5900ec435d8608160046a9d5
- [x] https://github.com/CityOfBoston/design-team-workflow/issues/306 recent cases search
- [x] https://github.com/CityOfBoston/311/issues/263 Nicer submitting page
- [x] https://github.com/CityOfBoston/311/issues/45 All Service Requests UI
- [x] https://github.com/CityOfBoston/design-team-workflow/issues/297 Combining 311 on the go and FAQ (desktop and mobile)

- [x] https://github.com/CityOfBoston/design-team-workflow/issues/298
- [x] https://github.com/CityOfBoston/design-team-workflow/issues/295
- [x] https://github.com/CityOfBoston/design-team-workflow/issues/275
