### ISSUE TITLE
Now Hiring: Update 2: Epic

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#363]
@reillyzlab, ideas for the next round of ads. I pitched thease to Lauren but got no response. We might want to shoot them now  so we can roll them out over time.

- Chardline Chanel-Faiteau (Education and Outreach Investigator Fair housing)
- Kerry Jordan (Television & Technology Manager)
- Patty McMahon (Registrar)
- Reilly Zlab (Product manager)
- Joseph Bagley (Archaeologist)
- Sarah figalora (content strategist)
- poll worker
- BTD worker
- Cop

https://waffle.io/CityOfBoston/av-club/cards/59ee062abb016300319152d5

Final list:
- [ ] Kerry Jordan (Television & Technology Manager)
- [ ] Joseph Bagley (Archaeologist)
- [ ] David Lenard (CTO) https://waffle.io/CityOfBoston/design-team-workflow/cards/5aa2ad80fe9729001bc6d164
- [ ] Shuttle driver
- [ ] EMS worker https://waffle.io/CityOfBoston/design-team-workflow/cards/5a6f41cf8d42fd0080320062
- [ ] Crossing gard
Parent of #590

**Comment by reillyzlab** [comment]
@sebastianebarb makes sense to me. I'd say run by OHR and then put them together when you have time.

I believe Darren had a few ideas as well.

**Comment by DACole** [comment]
I also have some good response around the mayors photographer as more of tech piece about how they have made the change from analog to digital. This piece could also highlight how there are these positions that in someway shadow the mayor. 

MassArt is loaning me a 16mm film camera, so the ideas was that the first part of the piece would be filmed on actual film and then when the change or switch in media happens in the story of the history of the mayors photography so does the content in the piece. 

Both Isabel and Don are interested in partaking in the project. 

A final ask would be to have Don bring one of his film cameras and take a present day portrait of the current mayor on film while the project speaks to the archival process of this city documents and what it means to be documenting history as it happens for future generations to learn from. 

I have roles of color film and black and white, supposedly the photographers only used color for special occasions or else it was documented in black and white. 

I have also been given a tour of the space of where the old dark room use to be, I just need to get the story on turnover time to process and create the similar work in the past as to what it takes now to put out images.

**Comment by DACole** [comment]
I don't know if this would be good cross over for the CC as it has to do with space place and longevity in a position as technology changes and your ability to adapt. Isabel expresses the DNC coming and being told they need to switch to digital cameras in 93-94 when the capabilities of the digital camera then were not what they are today.

**Comment by sebastianebarb** [comment]
@DACole before we start shooting we need you to source the Shuttle Driver and School crossing guard and have press confirm the list.  
Due by: Wednesday 11/1

- Kerry Jordan (Television & Technology Manager City Council)
- Senior Shuttle Driver  ( currency hiring )
- Joseph Bagley (Archaeologist)
- School crossing guard (currently hiring)
- and we are adding  Kelly McGrath at Parks.
No due date on videos yet.

Launch date:

**Comment by DACole** [comment]
I emailed Kerry, Joseph, and Kelly directly about availability. I also reached out to the departments for contacts of good people to work with for crossing guard and senior shuttle driver. 

Ill report back as the information comes in.
