### ISSUE TITLE
International Climate Summit: EPIC

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#618]
CONTACT:
Lauren Zingarelli <lauren.zingarelli@boston.gov>,
Carly Lindgren <carly.lindgren@boston.gov>
 
TIMELINE:
- [ ] March5: Official invitations (print and digital) sent to attending mayors including:
* Hotel information/registration
* General Agenda/topic areas
* Deliverable information
- [ ] April 25: Hotel registration due
- [ ] May 22: Digital presentations due
- [ ] May 29: Final pre-summit package sent to participants: Printed facebook
- [ ] Two day agenda and prep materials
- [ ] June 6-7: Summit

NOTES:
Caroline
- [x] Official Graphic for use on all materials
- [x] Invitation + Envelope (Print and Digital)
- [ ] Printed Facebook (to send to delegates)
- [ ] Deliverables and any prep materials
Sebastian
- [x] Programs 
- [x] Credentials / pass
- [ ] Wayfinding
- [x] Welcome screen 
- [x] Social media templates, quotes and general guidance.
- [ ] pop-ups and backdrops
https://docs.google.com/document/d/1ZcAcNr6W2bsgsJOn-1dpH0XBqJDHbh0SvxqWwwwrN9E/edit?usp=sharing

**Comment by sebastianebarb** [comment]
talked to the Press Office and here's the feedback I got to the design:

- less appearance of "flooding" in the B
- darker blues, especially as background where there's white text for contrast
- use sans serif font instead of italics
- add the Mayor's name to the front of the invitation

They also asked us to update the text to the working invite language now that we have more details on the Summit. Carly, do we have that updated language yet? If not, let me know and I can get to work on it.

**Comment by carolinestj** [comment]
mapbox map: 
https://api.mapbox.com/styles/v1/carolinestj/cjg58ihro7s6r2spsl8m7d7lj.html?fresh=true&title=true&access_token=pk.eyJ1IjoiY2Fyb2xpbmVzdGoiLCJhIjoiY2oxbm5laWd0MDBubDMzbWhtMDRnYTAzaSJ9.3cX-HlP4J1XxN-XX2g6lVQ#10.1/48.683026/2.485167/0

**Comment by sebastianebarb** [comment]
Hi all,

Thanks for your patience as we refine details for the Summit. Here's an update on where we're at for design and digital needs -

Official graphics for use on materials - all set with logo design. 
Invitation - all set; went out digitally last week.
Printed Facebook - scrapping this request; we no longer need.
Deliverables and any prep materials - if anything, this would look like a briefing for participants, and if so the template you created for documents may suffice.
Programs - may need designs for brief program, 1-3 pages.
Credentials - will need designs for at least 4 categories of participants/staff.
Wayfinding - may need designs; this will definitely include digital and maybe print. 
Social media templates, etc. - we will need to build for a press kit for participants; we can work with you on content now to think through the best approach for that.

In addition, we'd like designs for pop-ups and backdrops that are in line with the branding you created. We discussed an idea at one point in an earlier conversation that incorporated the global map. What do you need from us to move that forward?

For the website, I'd like to mimic the information we just finalized for our press release (includes speakers and quotes). Here's what I suggest. I can revise in Drupal, unless you have a specific layout in mind that would best support the new content. We'd have to hold on publishing this update until the press release is ready to go out, which could be Thursday or Friday this week. It doesn't have to be same time, but ideal.

Happy to talk through any of these items or all tomorrow. My schedule is flexible.

Best,
Lauren

**Comment by sebastianebarb** [comment]
New Notes / update 04/9
Banners are 24x80
- [ ] We'd also like pop-ups with condensed program text x6
- [x] Welcome banners x4  
- [x] Registration banners x 2
- [x] Press Area x2
- [x] Digital wayfinding 
- [ ] Trifold folder
- [x] custom lapel pins for mayors' names and what city they're from
- [x] other name tag system

**Comment by carolinestj** [comment]
New content may 11 
- [x]  notepads 
- [x] pens
- [ ] step and repeat backdrop
- [ ] New banner for toolkit
- [ ] lunch banner
- [ ] digital screen for funders

**Comment by sebastianebarb** [comment]
https://docs.google.com/spreadsheets/d/11YWKJ5nizXhaiDaN3dSuDb6IHfMAbd8C5GWdP-8K2is/edit#gid=1767435929

**Comment by sebastianebarb** [comment]
I just got guidance on the logos. As discussed, we can add to the digital screens, back of folder and welcome banner. All same level except BofA, which needs to be elevated and have the words "presented by" before it.

I think I need to add BU to the Google folder of logos. We'll also need quick review of these items before they go to print.

**Comment by sebastianebarb** [comment]
https://fta.ngam.natixis.com/

**Comment by sebastianebarb** [comment]
Attached is our most up-to-date agenda. We don't expect changes at this point. The names as written should appear the same on screen except for the following -

John Kerry, 68th U.S. Secretary of State
Anne Finucane, Vice Chairman, Bank of America
Gina McCarthy, 13th Administrator of the U.S. Environmental Protection Agency 

I'm copying Sebastian and Caroline who can share the branding with you. Sebastian and Caroline, Dave really liked the Summit logo and global map designs that I showed him today if you can share those. Anything else you think would be useful too.

+ Darren in case this content is also helpful to have and stayed looped in.

I'm back at BU tomorrow and available by cell during most of the day - 774-254-1472.

**Comment by sebastianebarb** [comment]
Here are the assets we'll need for the Summit's standard digital monitors before noon on Wednesday -

1. Thank-you slide - please use the same layout of logos as you did for the back of the folders.
2. Agenda slide 
3. Default slide - maybe this?
4. Welcome slide - totally your discretion
5. Registration slide - please include the text "Please proceed to the Metcalf Trustee Center for registration" 

I wonder if you'd be open to creating these in Canva, or sharing your Illustrator files with our team, so we can adjust and replicate as needed.
