### ISSUE TITLE
Translation Services connection-  EPIC

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#652]
- [ ]  Translation tagging in Design team workflow GitHub. This will provide us with stats on how many items we have translated through the design team and how often. (Assigned to Sebastian)
Parent of #654
https://waffle.io/CityOfBoston/design-team-workflow/cards/5aac19d60bcdc7001afaeba7

- [ ] Previously Translated Repo. This will be hosted as a joint folder between you me and any other City parties. We will have direct links and placement in the design portfolio. (Assigned to Sebastian)
Parent of #651
https://waffle.io/CityOfBoston/design-team-workflow/cards/5aac164a272039001ce6cca0

- [ ] Add dialect label when display language. (Assigned to Design Team) 
Parent of #731

- [ ] Add translation link to Hub in City Brand Guidelines (Waiting on direction from Manar) 
Parent of #653
 https://waffle.io/CityOfBoston/design-team-workflow/cards/5aac188458a18a001bd6d93f

- [ ]  Launage and accessibility specific icons .
Parent of #732

- [ ] OEM Emergency graphics translation
Parent of #732

- [ ] translation and digital resource space on The HUB--a website dedicated to Language and Communications Access. We mentioned this briefly, but thinking about it more concretely, this would be where the guides, checklists and other resources would be housed, and linked appropriately through the Branding, Plain Writing, Vendor, and VIP existing resources. Down the line, I envision this expanding to house the Citywide Policy, individual department plans, and another program specific information for use. 

- [x] Create a tagline for asking if citizens need "further assistance".  this might be a sign we should create for the Digital city hall signage? (Assigned to Manar).
"If you need interpretation or translation services, please contact first.last@boston.gov or 617-635-xxxx."

- [x]  Launage and accessibility logo .
- [ ] Hosting online 
Parent of #777
