### ISSUE TITLE
Emergency Response Graphics

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#656]
Parent of #732
The emergency list is here: https://docs.google.com/spreadsheets/d/1HM6zV5ATru0XLG7ltzkvxCJWwxKBkFJCFU274_iuPJk/edit?usp=sharing  

Project steps:
- [ ] List creation: Identify a wide variety of emergency Boston would need to respond to. Consolidate on a list and provided to multiple stakeholders for feedback.

- [ ] Emergency content development: Each emergency listed needs written copy to be added to the graphics and a sample tweet/text to coincide. Recommendations on imagery are welcome.

- [ ] Visual designation: Digital team and OEM should prioritize emergency based on severity to establish visual changes in graphics to help the user understand the situation. 

- [ ] VIsial creation:  Design team will create needed graphics. 

- [ ] Approval review of graphics and copy from OEM and stakeholders.

- [ ] Emergency graphics translation:  All graphics should be translated, creating a repository.

**Comment by sebastianebarb** [comment]
@reillyzlab I updated the project septs to reflect the full scope. I can be more detailed if needed.
