### ISSUE TITLE
Freedom Trail Signage: EPIC

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#675]
Stakeholders:
staylor@thefreedomtrail.org
chris.osgood@boston.gov

Due date 1: Fall 2018
(Filled out after our meeting)
Due date 2: 
(Filled out after our meeting)

Notes:
(Filled out after our meeting)

[Freedom Trail Foundation Official Brochure Final 2017.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46ce869f26868ca4cfddad42ad51b0b2265329772810aa247ec5cc2eb94b78080e035ede03070c1cb9bbdc3bd0ef6221d64c09edd06a4d68d47d53f3e2d74cfb13b0328e48d6b6bb8f19c7ed3527b28bda4d3f1e0749dcfb5b66a98b57da1aa715b51208fd596321f47c247d4f9e1f702e696324a2ffdb50818362b6f7.pdf)

All files:
https://drive.google.com/drive/folders/1Mc_sDM47Xd0xFCA4taqXPRQLBIvk6Nqy?usp=sharing

Parent of #701
Proposal:
https://docs.google.com/document/d/1ISDheCs91W_6AT0AR92MW1kNM3EDBV_Vl0mIwDBTZJw/edit?usp=sharing

Wayfinding design
Parent of #702

Design feild testing
Parent of #727

Open comment perioud 
Parent of #703

Digital interaction plan
Parent of #704

Physical problems with Freedom trail (for internal DPW use)
Parent of #725

Social media:
DIGITAL TEAM BLOG ON BOSTON.GOV:
Parent of #705

MONTHLY #BOSTONUNCOVERED VIDEO
Parent of #706

Final PRESS RELEASE
Parent of #707

Report on Physical trail
Parent of #723

Report on freedom trail site interaction
Parent of #729

Report on freedom trail sign palcement
Parent of #728

Freedom trail brand guidelines
Parent of #734

Remake Freedom trail emblem
Parent of #735

**Comment by carolinestj** [comment]
Notes from meeting  4/4/18 (feel free to add if I forgot anything) 

Freedom trail signage (current) 
- two-sided 
- made of porcelain  
- many are broken, have stickers on them or the final is bent 
- installed in 1998 
- signage not present consistently at historic sites
- bronze medallions are consistent and located in front of each historic site
- over 16 sites

New asks: 
- create consistent, new signage across all sites (old signage isn't historic so new signage doesn't have to mimic; finials are easily breakable and can be taken off) 
- add wayfinding signage where needed
- adding signage directing to accessible entrances
- brainswarm web application (e.g. non-native app) with location services, highlighting historic sites on route/nearby as well as accessible entrances/routes on the Trail.

Deadline:
Proposal deadline two weeks from now
Fall 2018: Period of public comment and interaction 
Spring 2019: Full project launches 

Check-ins: 
- Every two weeks unless something else comes up
- Next meeting with FTF will go over the initial proposal 
- Stakeholders meeting (all 16 sites) after the first FTF meeting

**Comment by carolinestj** [comment]
concerns from people: 

- which sites are free 
- visiting hours
- where is the entrance

**Comment by sebastianebarb** [comment]
Historical notes:
https://www.flickr.com/photos/cityofbostonarchives/albums/72157659598569715

**Comment by sebastianebarb** [comment]
As promised, the following  are the credentials for you to review the website (in particular, please note the bottom of each sites’ page there is the distances from one site to another).  A lot of pages are still under construction.

http://freedom-trail.ohodev.com/

user: admin

pass: ohosite1100

**Comment by sebastianebarb** [comment]
Potential roadblocks:
- [ ] Web application
- [ ] Will we need 3d renders made of signage options?
- [ ] We need a voting system for the open comment period 
- [ ] We will need to fabricate sign for the open comment period
- [ ] We need schematics made of signage options

**Comment by sebastianebarb** [comment]
@carolinestj Below are next steps details, let me know if you have questions. 

- [ ] Please add an indication for next sites in both directions to all signs
- [ ] We need two sets of three posters to user test. Set 1) Using icons, create a poster with a map of the whole freedom trail. One site poster containing guiding book info about the site it's at (Fan Hall in this case) and a general wayfinding image. Set 2) Should not have icons and should contain the same information. However, the layout should be different to test against.

**Comment by sebastianebarb** [comment]
https://docs.google.com/spreadsheets/d/1oBpGpb2cnVTjDllqLnTh1zeJFpxuoxQ_lrCPmTmb29k/edit#gid=2038516341

**Comment by jiaoruijiang** [comment]
Site interaction report: 
https://docs.google.com/document/d/1mBKnthYLJiIj8oYkqTx56eS3Oj-P1PPcS_PO67c7Xjs/edit?usp=sharing
Signage placement report: https://docs.google.com/document/d/19jjJArABlxd4YTUke9SvXdVGwf11E4QG2tuFRUQ1QC0/edit?usp=sharing
Physical issues report: https://docs.google.com/document/d/1Q1kOZGLU77wzyOet9m20UymrOObtsuOGqi5HIgI9HMQ/edit?usp=sharing
Physical issues spreadsheet: https://docs.google.com/spreadsheets/d/1S8r3zKE9elkn7bn7BPIS3IBOfu9TlfQ3HEzFiP-Oyng/edit?usp=sharing
