### ISSUE TITLE
2018 Holiday B's EPIC

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#808]
Asian holidays:
Parent of #778

Holiday ‘B’ Contest:
Parent of #662

Other:
- [ ] Comic-con
- [x] Pax east
- [x] September equinox
- [x] Halloween (new)
- [x] Qing Ming Festival (April
- [x] Nov 6 Diwali/Deepavali
- [ ] Dec 26	Kwanzaa (until Jan 1)
- [x] Mar 2 Read Across America Day
Parent of #823
- [x] Apr 16 Patriot's Day
