### ISSUE TITLE
Reimagining The Elderly Commission: EPIC: Age Strong

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#810]
Contact: cassandra.baptista@boston.gov 
Due: Nov- Dec

- [x] Logo and Name
Parent of #818

- [ ] Brochure
Parent of #812

- [ ] Postcard
Parent of #870

- [ ] Event banner / Table cloths
Parent of #813

- [ ] Giveaways (logo added only)
Parent of #814

- [ ] Staff shirts and Jackets - Parent of #815

- [ ] Intro video - https://waffle.io/CityOfBoston/av-club/cards/5b966e6f967913001cc39db2

- [ ] Van Wrap
Parent of #869

- [ ] Ad campaign 
Parent of #871

- [ ] Age stong housing intake form 
Parent of #1027

- [ ] Phase 2 Reimagining The Elderly Commission: EPIC
Parent of #817

More details can be found here: https://drive.google.com/drive/folders/1ZJDn48YVPngUk8EJUHeeXM4VbdUXrON-?usp=sharing_eil&ts=5b842780

Or here:
https://drive.google.com/drive/folders/1ZJDn48YVPngUk8EJUHeeXM4VbdUXrON-?usp=sharing

Parent of #1087

**Comment by sebastianebarb** [comment]
Notes from meeting Nov 20th
What
- Circles, things coming full circle
- Arrows,  Connections
- Large quotes
- Icons

**Comment by sebastianebarb** [comment]
[871_03_Age strong.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0c3cb1cd2d096aeeeba03b749e29b2741653f6b14b1247a80e03cfd183954580c4eab440d5841f4fbdc2bf3b43d70880d5ee9d73e5666da2f53fde6d640e258f075c95d8fa4bd8246c1ed3926ef8f874f3e18041080ed10.pdf)

**Comment by sebastianebarb** [comment]
Feedback on Design Concepts from Meeting on 12/10:

- [ ] Collectively, we liked Idea 3 best, but would like to possibly integrate circles as a design feature to use sometimes. 
- [x] We would like to see Idea 3 with the people in full color, instead of the blue treatment.
- [ ] We like the idea of using big pull quotes from constituents, but the treatment of the quotation marks here confused some people (it look like 6699), so maybe we lose these quotes or use a different treatment when we use quotes.
- [x] We want the main line to say, “In Boston, we Age Strong”
- [x] We love your sub-headline, “Age With Us”
- [ ] For the folder treatment, we might want to play with some things so not every side of the folder is white; maybe there is a panel in blue with the Mayor’s letter, etc.

**Comment by sebastianebarb** [comment]
[Design concepts Age Strong.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46cc91892a858de98ce6b140a14de487696720766937b7397f8be46af3006b1300051bff054a5556f9feda2ba1b369778f5409b8d1385d75c63f40f9bc844cb613a632c91edbe2e3d7158abd7f37ed998e48341f001c8df75f36a09f49c850f359ac.pdf)

**Comment by sebastianebarb** [comment]
![Age_strong_logo_02-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c9939f1c9197bb80e7b87ca852f79b1616753e7955e1673295f127b54778154d555ca9460b5f43f9ac8e2eaeb46970df5e0aedd33c0a70c06e18bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8b4a371c021e89fa5a36a38b06.png)

**Comment by sebastianebarb** [comment]
Uppaknee header for e-newsletters
letterhead
envelopes
notecards
one-pager/annual report header
signature line template with the logo and new name would be helpful to have ready to go before Jan. 13th! Thanks, Cassy

We also do Birthday Certicates and Proclamations from the Mayor that need some pizzazz. We'd be looking to have both horizontal and vertical templates, depending on the folder we order.

**Comment by sebastianebarb** [comment]
Phase one, before SOTC
- [ ]  A white version of logos for jackets
- [x]  Facebook cover image
- [x]  Facebook post image for the announcement 
- [ ]  Lobby screen slide
- [x] Twitter cover image
- [x] Tweet image post
- [x] YouTube cover image

Phase one, after SOTC
- [ ] Mockups for MV1 vehicle with a small, medium, and large treatment
- [ ] Folder design: 
https://docs.google.com/document/d/1EXhP5AnDSCM3svkhmbHSdBNuSVdmqo1S8d1qGuI9oa8/edit?usp=sharing
- [ ] Pop up banners 
- [ ] Table cloth
- [ ] Giveaways (logo added only)
- [ ] Brochure
- [ ] Binesscards, letterhead etc will be handled by purchasing.
- [ ] template for staff signature lines
- [ ] Twitter cover image
- [ ] Tweet image post
- [ ] YouTube cover image
- [ ] guidelines for our colors, photos, etc. 
- [ ]  "Age Strong" branded slides (for staff presentations)
- [ ]  Age Strong one-pager template and newsletter/annual report template (basically just adding our new icon and name to your existing suite of materials)
- [ ] business cards- (Emily and Jeanethe spoke about bumping up the font size and possibly removing the italics so our constituents can read it more easily. Please let me know how to move forward.)
Under Phase 3:

Phase two 
- [ ] Ad campaign 
- [ ] Intro video
- [ ]  Lobby materials: https://docs.google.com/spreadsheets/d/10Vu-ek3SaR6p8MjttkfeBAVI08HlEIO0BJvgVod7U-Y/edit?usp=sharing
 - [ ] coordinate ad placements designs for City anti-ageism campaign for May

**Comment by sebastianebarb** [comment]
Following up: 

Logo treatment files for age strong for shirts (with age strong above city in bold to identify us more clearly)--When could you get us this file? I know our office manager is eager to get our shirts ordered. 

Brand guidelines look great. As we keep confirming details, there will probably be more to add. 

Our powerpoint template is a good shell for us to continue to build out, thanks.

Could you resend the one pager template? I couldn’t find it.

You asked about quotes from seniors. I just sent you a document with quotes today and highlighted ones that could work: https://docs.google.com/spreadsheets/d/1pHYezKeZQDbeM31MknoPPLnB1nlATO4zB5hRWivCCag/edit?usp=sharing

Business cards redesign- I'll schedule a meeting for us on Tuesday. 

Electronic version of our letterhead so we can print or pdf/email letters, etc.- you said you'll work on this

I have added suggested text for banners here: https://docs.google.com/document/d/1QUYW0NlcfTk-3_90Szdwt8t60GhwsecSdMvjhb3z3oA/edit?usp=sharing

Drafted text for the simple brochure is here: https://docs.google.com/document/d/1T2Nc9npDqeATc3n6P80EJl8liZ5iPwKOveUCVSSggFI/edit?usp=sharing

How to hold commercial spots, MBTA bus shelters/t ads for the anti-ageism campaign in May for Older Americans month- I will connect with Sarah


Thanks for your ongoing support on this project,

**Comment by sebastianebarb** [comment]
https://docs.google.com/spreadsheets/d/1pHYezKeZQDbeM31MknoPPLnB1nlATO4zB5hRWivCCag/edit?usp=sharing

**Comment by sebastianebarb** [comment]
Following up: 

Logo treatment files for age strong for shirts (with age strong above city in bold to identify us more clearly)--When could you get us this file? I know our office manager is eager to get our shirts ordered. 

Brand guidelines look great. As we keep confirming details, there will probably be more to add. 

Our powerpoint template is a good shell for us to continue to build out, thanks.

Could you resend the one pager template? I couldn’t find it.

You asked about quotes from seniors. I just sent you a document with quotes today and highlighted ones that could work: https://docs.google.com/spreadsheets/d/1pHYezKeZQDbeM31MknoPPLnB1nlATO4zB5hRWivCCag/edit?usp=sharing

Business cards redesign- I'll schedule a meeting for us on Tuesday. 

Electronic version of our letterhead so we can print or pdf/email letters, etc.- you said you'll work on this

I have added suggested text for banners here: https://docs.google.com/document/d/1QUYW0NlcfTk-3_90Szdwt8t60GhwsecSdMvjhb3z3oA/edit?usp=sharing

Drafted text for the simple brochure is here: https://docs.google.com/document/d/1T2Nc9npDqeATc3n6P80EJl8liZ5iPwKOveUCVSSggFI/edit?usp=sharing

How to hold commercial spots, MBTA bus shelters/t ads for the anti-ageism campaign in May for Older Americans month- I will connect with Sarah

**Comment by sebastianebarb** [comment]
First drafts Timeline:
- #869 Vehicle wrap 2/26
- #812 Folder 2/27
- #870 Postcard 3/1

Pending further collaboration
-  Intro video - https://waffle.io/CityOfBoston/av-club/cards/5b966e6f967913001cc39db2
- #871 Ad campaign

**Comment by sebastianebarb** [comment]
Logos: Can we have a couple more versions of our logo (Exported to all formats)?
A version that looks that has city of boston, age strong commission, and mayor's name stacked
in black
in white with the red line
A version that has just the age strong commission and mayor's name stacked
in black
in white with the red line
See below for examples of what i mean
Banners: Sorry, was told these were done and things backtracked a little...Can you update the banner files with the following:
Can you remove the banner design from the file with the two ladies dancing in converse?
Can all the banners have the new logo that has city of boston, age strong commission, and mayor's name stacked
Vehicles: We like option 1 for vehicles. The team does want to see the treatment for the Mayor's name on the back of the vehicles. Something important to note: we have a few vehicles (like the Commissioner's vehicle and our events van) that we will probably want to remove "Transporting Boston's..." and replace with, "In Boston, we Age Strong," since those vehicles won't be meant for taking people around. Also, did I send you the list/spreadsheet of all vehicles in our fleet? I thought I did but want to double check you have what you need. 
image.png

Three lines of stacked text for logo:

image.png
2 lines of stacked text logo with age strong and Mayor's name:

image.png
