### ISSUE TITLE
End of the year projects (EPIC)

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#966]
- [x] Establish contact on older projects
Parent of #963

- [ ] Digital end of the year report
Parent of #962

- [x] Digital team Happy New Year card
Parent of #961

- [x] Update roadmap
Parent of #967

- [x] canva class
Parent of #971

- [ ] Update Stratigic plan
Parent of #860

- [x] Darren Ticket Re-file
Parent of #996
